import {
    PATH_CALENDAR,
    PATH_INBOX,
    PATH_ACCOUNT,
    PATH_AUTH,
    PATH_BLOG,
    PATH_CAREERS,
    PATH_CHANGELOG,
    PATH_CONTACTS,
    PATH_CORPORATE,
    PATH_DASHBOARD,
    PATH_DOCS,
    PATH_ERROR,
    PATH_FILE,
    PATH_GITHUB,
    PATH_INVOICE,
    PATH_LAYOUT,
    PATH_PROJECTS,
    PATH_SOCIAL,
    PATH_START,
    PATH_SUBSCRIPTION,
    PATH_USER_MGMT,
    PATH_USER_PROFILE,
    PATH_LANDING
} from "./routes.ts"

const DASHBOARD_ITEMS = [
    {title: 'default', path: PATH_DASHBOARD.default},
    {title: 'projects', path: PATH_DASHBOARD.projects},
    {title: 'ecommerce', path: PATH_DASHBOARD.ecommerce},
    {title: 'marketing', path: PATH_DASHBOARD.marketing},
    {title: 'social', path: PATH_DASHBOARD.social},
    {title: 'bidding', path: PATH_DASHBOARD.bidding},
    {title: 'learning', path: PATH_DASHBOARD.learning},
    {title: 'logistics', path: PATH_DASHBOARD.logistics},
]

export {
    PATH_CALENDAR,
    PATH_USER_MGMT,
    PATH_INBOX,
    PATH_PROJECTS,
    PATH_LAYOUT,
    PATH_CORPORATE,
    PATH_CONTACTS,
    PATH_DASHBOARD,
    PATH_CHANGELOG,
    PATH_CAREERS,
    PATH_ACCOUNT,
    PATH_GITHUB,
    PATH_AUTH,
    PATH_INVOICE,
    PATH_BLOG,
    PATH_ERROR,
    PATH_DOCS,
    PATH_SUBSCRIPTION,
    PATH_USER_PROFILE,
    PATH_FILE,
    PATH_SOCIAL,
    PATH_START,
    PATH_LANDING,
    DASHBOARD_ITEMS
}