import {
  BiddingDashboardPage,
  DefaultDashboardPage,
  EcommerceDashboardPage,
  MarketingDashboardPage,
  ProjectsDashboardPage,
  SocialDashboardPage,
} from './dashboards';
import HomePage from './Home.tsx';
import {
  CorporateAboutPage,
  CorporateContactPage,
  CorporateFaqPage,
  CorporateLicensePage,
  CorporatePricingPage,
  CorporateTeamPage,
} from './corporate';
import SitemapPage from './Sitemap.tsx';
import {
  UserProfileDetailsPage,
  UserProfilePreferencesPage,
  UserProfileInformationPage,
  UserProfileSecurityPage,
  UserProfileActivityPage,
  UserProfileActionsPage,
  UserProfileHelpPage,
  UserProfileFeedbackPage,
} from './userAccount';
import {
  SignUpPage,
  SignInPage,
  WelcomePage,
  VerifyEmailPage,
  PasswordResetPage,
  AccountDeactivePage,
} from './authentication';
import {
  Error404Page,
  Error500Page,
  Error403Page,
  Error400Page,
  Error503Page,
  ErrorPage,
} from './errors';

export {
  DefaultDashboardPage,
  HomePage,
  ProjectsDashboardPage,
  EcommerceDashboardPage,
  MarketingDashboardPage,
  SocialDashboardPage,
  BiddingDashboardPage,
  CorporateAboutPage,
  CorporateTeamPage,
  CorporateFaqPage,
  CorporateContactPage,
  CorporatePricingPage,
  CorporateLicensePage,
  SitemapPage,
  UserProfileDetailsPage,
  UserProfilePreferencesPage,
  UserProfileInformationPage,
  UserProfileSecurityPage,
  UserProfileActivityPage,
  UserProfileActionsPage,
  UserProfileHelpPage,
  UserProfileFeedbackPage,
  SignUpPage,
  SignInPage,
  WelcomePage,
  VerifyEmailPage,
  PasswordResetPage,
  AccountDeactivePage,
  Error500Page,
  Error404Page,
  Error403Page,
  Error503Page,
  Error400Page,
  ErrorPage,
};
