import {
  CampaignsCard,
  RecentUsersCard,
  GetStartedCard,
  OrdersChart,
  LatestOrdersCard,
  EarningsCard,
  SubscribersChart,
  WeeklyActivityCard,
  TasksChartCard,
  TasksListCard,
} from './default';
import { RevenueCard, PostsCard, ProjectsCard } from './shared';
import { CustomerReviewsCard } from './ecommerce';
import { ProjectsCountCard, ProjectsTable, ClientsTable } from './projects';
import {
  StatsCard as MarketingStatsCard,
  VisitorsChartCard,
  SocialStatsCard as MarketingSocialStatsCard,
  CampaignsActivity,
  CampaignsAdsCard,
  AudienceLocationChart,
} from './marketing';
import {
  SocialStatsCard,
  FollowersChart,
  LikesChart,
  DevicesCardChart,
  MilestonesCard,
  CommentsCard,
} from './social';
import {
  AuctionCarousel,
  CreatorsCard,
  TopItemsCard,
  TransactionsCard,
  CategoriesCard as BiddingCategoriesCard,
} from './bidding';
import {
  StatsCard as LearningStatsCard,
  CoursesCard,
  CoursesCarousel,
  StudyStatisticsCard,
  ProgressCard,
  ExamsCard,
  CommunityGroupCard,
} from './learning';
import {
  StatsCard as LogisticsStatsCard,
  DeliveryTableCard,
  DeliveryAnalyticsCard,
  DailyPlanCard,
  TruckListCard,
  DeliveryRequestCard,
} from './logistics';

export {
  CampaignsCard,
  LatestOrdersCard,
  ProjectsCountCard,
  RevenueCard,
  ProjectsCard,
  OrdersChart,
  ProjectsTable,
  CustomerReviewsCard,
  ClientsTable,
  EarningsCard,
  GetStartedCard,
  RecentUsersCard,
  SubscribersChart,
  MarketingStatsCard,
  VisitorsChartCard,
  SocialStatsCard,
  CampaignsActivity,
  CampaignsAdsCard,
  AudienceLocationChart,
  MarketingSocialStatsCard,
  FollowersChart,
  LikesChart,
  DevicesCardChart,
  PostsCard,
  MilestonesCard,
  CommentsCard,
  AuctionCarousel,
  CreatorsCard,
  TopItemsCard,
  TransactionsCard,
  BiddingCategoriesCard,
  LearningStatsCard,
  CoursesCard,
  CoursesCarousel,
  StudyStatisticsCard,
  ProgressCard,
  ExamsCard,
  CommunityGroupCard,
  LogisticsStatsCard,
  DeliveryTableCard,
  DeliveryAnalyticsCard,
  DailyPlanCard,
  TruckListCard,
  DeliveryRequestCard,
  WeeklyActivityCard,
  TasksChartCard,
  TasksListCard,
};
