export { DefaultDashboardPage } from './default.tsx';
export { ProjectsDashboardPage } from './projects.tsx';
export { EcommerceDashboardPage } from './ecommerce.tsx';
export { MarketingDashboardPage } from './marketing.tsx';
export { SocialDashboardPage } from './social.tsx';
export { BiddingDashboardPage } from './bidding.tsx';
export { LearningDashboardPage } from './learning.tsx';
export { LogisticsDashboardPage } from './logistics.tsx';
export { default as AnalyticsDashboardPage } from './analytics.tsx';
export { default as HealthcareDashboardPage } from './healthcare.tsx';
export { default as FinanceDashboardPage } from './finance.tsx';
